### ISSUE TITLE
Remember me check box

### ISSUE THREAD

**Issue by ramanparashar** [InfluenceIO/frontend#102]
![image](https://user-images.githubusercontent.com/29310956/40827587-a03672f8-659b-11e8-85d4-cabb9231e043.png)

The remember me checkbox is not working, and hence I can't move fwd on this.

also cut down the size of the checkbox to make it look appealing.

You could also remove the remember me since it is creating friction in the sign-up process.

**Comment by GAUTAMRAJU15** [comment]
so we have to remove it ?

**Comment by ramanparashar** [comment]
@GAUTAMRAJU15  Yes

**Comment by GAUTAMRAJU15** [comment]
ok sir will be done

**Comment by GAUTAMRAJU15** [comment]
this one is done. i will push it along with sign in page
