### ISSUE TITLE
Google and Facebook Sign Up Missing (Signup page)

### ISSUE THREAD

**Issue by ramanparashar** [InfluenceIO/frontend#103]
![image](https://user-images.githubusercontent.com/29310956/40827700-049d6292-659c-11e8-932a-9b5c8d04a522.png)

It is important to have google and facebook sign up in the signup section of the website. Please add these things.

Study couple of competition websites to see how you can insert the google and fb icons, sign up wise.

Like how to accommodate them.

**Comment by GAUTAMRAJU15** [comment]
closing the  issue as they are not required by the developer team
