### ISSUE TITLE
Schedule A Demo Popup

### ISSUE THREAD

**Issue by ramanparashar** [InfluenceIO/frontend#109]
![image](https://user-images.githubusercontent.com/29310956/40873342-13bfab1e-667c-11e8-861e-77dd360c1a73.png)

Create a popup like this targeted towards our brand.

Find good HQ images from internet sources that looks like a customer care person and tweak it to our brand.

Just create a popup.

and then get back to me I will tell when to sequence it.

**Comment by GAUTAMRAJU15** [comment]
done
