### ISSUE TITLE
Schedule a demo page

### ISSUE THREAD

**Issue by ramanparashar** [InfluenceIO/frontend#110]
https://www.zendesk.com/demo/

Please duplicate this page and check with @maektwain on how you'd go about it.

The whole website is being built using builder.

So maybe builder should be used, or custom design is the way out.

**Comment by GAUTAMRAJU15** [comment]
html page is being made ,  have to convert that into the react component

**Comment by ramanparashar** [comment]
please convert it :D

**Comment by GAUTAMRAJU15** [comment]
ok sir :D

**Comment by GAUTAMRAJU15** [comment]
done
