### ISSUE TITLE
Footer design and adjustment

### ISSUE THREAD

**Issue by ramanparashar** [InfluenceIO/frontend#111]
![image](https://user-images.githubusercontent.com/29310956/40873726-aeb4d19c-6683-11e8-9bde-615e80968e85.png)

Make the footer section of the website like Zendesk.

*Reason:* Because we'll be accommodating a lot of functions on the website.

Go to this link and see the footer. and make our footer also look like this.

https://www.zendesk.com/demo/

With a special focus on cutting down the font size of the items to accommodate more things.

**Comment by GAUTAMRAJU15** [comment]
changes made work complete
