### ISSUE TITLE
Animation Loading

### ISSUE THREAD

**Issue by ramanparashar** [InfluenceIO/frontend#245]
Animated loading of numbers in bulk signup.

![image](https://user-images.githubusercontent.com/29310956/43463353-02177042-94f6-11e8-9093-ee15388d94f9.png)

**Comment by Devilla** [comment]
like they start from 0 and ends up current value?

**Comment by ramanparashar** [comment]
@Devilla Yes, duplicating it exactly like proof has done it, Please check their style of loading and study it and duplicate that style of loading in the bulk sign up.

Please take a fresh pull and resolve this issue. 😄

**Comment by maektwain** [comment]
What is this issue about is it resolved or waiting for some work to be finished please tag it or close it .
