### ISSUE TITLE
Dashboard> 'Help' button to be added

### ISSUE THREAD

**Issue by ramanparashar** [InfluenceIO/frontend#29]
![image](https://user-images.githubusercontent.com/29310956/39423089-f9155c76-4c8d-11e8-8e6e-c3495089f88d.png)

Can you add a help button like this.

And once that is added please connect it to a popup form like this.

https://www.dropbox.com/s/t09i29vpxnpbfyh/Screenshot%202018-04-30%2015.41.43.png?dl=0

**Comment by ShankyRana** [comment]
8-12 hours

**Comment by maektwain** [comment]
@ShankyRana @ramanparashar as of now we can connect it with Zendesk and then later on we will create a modal box where customer can do it within the App.
