### ISSUE TITLE
Facebook And Google Login Not Working

### ISSUE THREAD

**Issue by ramanparashar** [InfluenceIO/frontend#32]
![image](https://user-images.githubusercontent.com/29310956/39957061-0827a69e-560a-11e8-9161-0670d5a9200c.png)

a) Login not working.
b) the buttons don't look aesthetically appealing as per the whole website scheme and theme goes.
c) There is no spacing between both the login buttons.
d) 

Ref copy of how hygiene should look like:

https://www.dropbox.com/s/6s5jafbe0g1l0vp/Screenshot%202018-05-12%2017.31.03.png?dl=0

**Comment by ShankyRana** [comment]
1-2 hours
