### ISSUE TITLE
Popup Oriented issues

### ISSUE THREAD

**Issue by ramanparashar** [InfluenceIO/frontend#33]
![image](https://user-images.githubusercontent.com/29310956/39957123-f5d8028a-560a-11e8-9737-c0b57a9df814.png)

a) The default image should be changed (refer to @raman on this)
b)  years ago should be changed to " hours ago " with real information being displayed on when exactly it was displayed.
c) Location fetching should happen in Popups.

**Comment by ShankyRana** [comment]
default image: completed
years ago: completed
Location: 5-6 hours

**Comment by maektwain** [comment]
You should check for the location(IP, GEOIP) part from the analytics code.
