### ISSUE TITLE
Websites with pixel NOT showing.

### ISSUE THREAD

**Issue by ramanparashar** [InfluenceIO/frontend#34]
![image](https://user-images.githubusercontent.com/29310956/39957225-11820fc4-560d-11e8-8999-1e1aad8cab0a.png)

a) I have saved one website and have applied the code to one website and even then it is not showing up in the dash section.
b) Notification shown is not loading up numbers wise.
c) Unique visitors for this particular account and the website on which I am loading up is also not showing up.
d) get rid of the line " get one of our experts to do it for you "

**Comment by maektwain** [comment]
#35
