### ISSUE TITLE
Dashboard> New> Install Pixel> Verify Pixel Status NOT working

### ISSUE THREAD

**Issue by ramanparashar** [InfluenceIO/frontend#37]
![image](https://user-images.githubusercontent.com/29310956/39957647-f922c480-5613-11e8-92b8-6cff6b4e75d5.png)

a) Verify pixel status option is not working :: Default button color = Yellow;  If Verification success then Button Color = Green;  If Verification Fail then Button Color = Red.

**Comment by ShankyRana** [comment]
1-2 hours
