### ISSUE TITLE
 Notifications block UI upgrade 

### ISSUE THREAD

**Issue by ramanparashar** [InfluenceIO/frontend#38]
![image](https://user-images.githubusercontent.com/29310956/39957782-0212851a-5616-11e8-807a-3538fc390559.png)

a) 'Configure Button' -- Button should be small & appropriate set (font style wise)
b) Toggle button should also become active when:  we click on 'configure' > go inside & make/save some changes

**Comment by ShankyRana** [comment]
Need design mockup.

**Comment by ShankyRana** [comment]
Please provide a mockup for this, then changes can be made accordingly.
