### ISSUE TITLE
Dashboard> New> Capture Leads> Rework required

### ISSUE THREAD

**Issue by ramanparashar** [InfluenceIO/frontend#40]
![image](https://user-images.githubusercontent.com/29310956/39957936-eaf894f2-5618-11e8-88b1-c30cfba4415b.png)

a) Need to redo this page.

**Comment by ramanparashar** [comment]
Should have a more intuitive UI... See the video of Useproof's dashboard for comparison.

**Comment by ShankyRana** [comment]
6-10 hours
