### ISSUE TITLE
Popup functioning issues -- Related to Behaviour

### ISSUE THREAD

**Issue by ramanparashar** [InfluenceIO/frontend#48]
![image](https://user-images.githubusercontent.com/29310956/39959845-8b087d24-5635-11e8-926f-f625e0252de4.png)

The issue of the popup that's coming out to be on this site is that.

a) The ideal show up time for the popup is 4-5 mins.
b) The stay time of each popup is also very high.
c) The popups should all have a stable stay time (Please refer to raman for timings of this)
d) The Popups should have come in with a fade in and fade out sort of style.
e) Other popups are not circulating at all.

![image](https://user-images.githubusercontent.com/29310956/39960051-0ba34ca4-5639-11e8-9b41-a761e9c710cc.png)

Why is this popup showing, There hasn't been a sign up of this sort.

**Comment by ShankyRana** [comment]
fade in and fade out: 1-3 hours
other issue resolved
