### ISSUE TITLE
Notification Popup: Recent Signups

### ISSUE THREAD

**Issue by ramanparashar** [InfluenceIO/frontend#5]
Objective:  To show 'Recent user signups' data in the notification 
 {Notification can be shown on both PC & Mobile websites}

**Popup structure**:  

Dimensions (for PC)
1st line - 12 px
2nd line - 10 px
3rd line - 10 px
Margin between 1st & 2nd lines - 8 px
Margin between 2nd & 3rd lines - 12 px

![notification type](https://user-images.githubusercontent.com/29310956/39136252-703f4f38-4738-11e8-8c36-80db18bd6111.png)

Text Area ::- {Vertical - top padding - 9.5px; bottom padding - 8px; Horizontal Padding - 0px }

Radius ::- Same as Useproof notification

****
Text Decoration & Aesthetics-- Similar to Useproof notification: 

![useproof notification](https://user-images.githubusercontent.com/29310956/39137088-659f4900-473a-11e8-8930-900496832864.png)

****
**Popup default behaviour**:

Delay before popping of first notification = 3 sec
Delay between subsequent notifications = 2 sec
Display time for each notification = 4 sec
Default timestamp for Signup data = Last 24 hour signups

Mixing between 3 notification types::   6:1:1 = Recent Signups : Live Visitor : Bulk Signups

**Comment by maektwain** [comment]
From where did you get all of this design looks interesting . (I am talking about dimension not Natalie 😁 )
