### ISSUE TITLE
Manage notifications issue

### ISSUE THREAD

**Issue by ramanparashar** [InfluenceIO/frontend#55]
![image](https://user-images.githubusercontent.com/29310956/40000375-4898de3c-57a9-11e8-9006-b0111c05be46.png)

Issue:

a) I have added these 3 websites, technically all three are same websites, but here I don't know which one is the verified pixel and which ONE is working here rn.
b) also when I click on the URL Stagephod, it opens a " open in new tab manner " and then opens the dashboard setting for that particlar website (technically clicking on this website shouldn't open up anything in new url)

**Comment by ShankyRana** [comment]
4-6 hours
