### ISSUE TITLE
Campaign name should be there instead of website name

### ISSUE THREAD

**Issue by ramanparashar** [InfluenceIO/frontend#56]
![image](https://user-images.githubusercontent.com/29310956/40104810-e9f2b35a-590e-11e8-9bf8-c4329fe4166c.png)

This should be numerically displayed.

**Comment by ShankyRana** [comment]
numerically like a list or so.

**Comment by ramanparashar** [comment]
Display only Active Campaign Names

Title: Active Campaigns
