### ISSUE TITLE
Website opening issue

### ISSUE THREAD

**Issue by ramanparashar** [InfluenceIO/frontend#69]
![image](https://user-images.githubusercontent.com/29310956/40235746-ce9e3e24-5ac8-11e8-83aa-2140222e11bd.png)

The website doesn't open on a lot of occassions in my opera

I need to refresh it or enter the details in the browser again to get it going.

**Comment by maektwain** [comment]
I think this is more like an issue related to internet speed, could you please log the developers inspect element details from the browser.

While creating an issue like this.

Thanks
