### ISSUE TITLE
'Bulk Signups' Notification Popup

### ISSUE THREAD

**Issue by ramanparashar** [InfluenceIO/frontend#7]
Dimensions same as 'Recent Signup' notification type, in issue #5

Only difference is Icon image & Popup radius

**## Useproof's notification (copy this):**

![bulk signups](https://user-images.githubusercontent.com/29310956/39142881-96fe7f66-4749-11e8-879d-5a59fcd1e476.png)

**Comment by maektwain** [comment]
This seems like the number of count for people who signed up for the service.
