### ISSUE TITLE
'Signup' happening through Facebook/Google 'Signin' (bypassing Payment)

### ISSUE THREAD

**Issue by ramanparashar** [InfluenceIO/frontend#72]
> Anyone can Signup into the account simply through Facebook/Google Signins.

> Facebook Sign-in not working in Mac (Safari)

> Google Sign-in not working in Windows

**Comment by maektwain** [comment]
So, ok @ramanparashar @ShankyRana I think this needs to be well thought and expressed clearly before.

1. Check customer has already account 
2. I think social account should be associated to user.

I think we need to start working on the payment API asap.
