### ISSUE TITLE
Dashboard> New> Capture Leads : URL addition by pressing 'Enter'

### ISSUE THREAD

**Issue by ramanparashar** [InfluenceIO/frontend#82]
1. Should be able to Add urls by just pressing 'Enter'.

2. Can Add multiple urls at the same time by writing urls with a 'space' between them.

![issue - capture leads](https://user-images.githubusercontent.com/29310956/40601044-5e85f716-6208-11e8-9694-f16d5dc9775f.png)

**Comment by ShankyRana** [comment]
Second point doesn't make scene from customer point of view or usage.
