### ISSUE TITLE
Features not working properly

### ISSUE THREAD

**Issue by ramanparashar** [InfluenceIO/frontend#97]
![image](https://user-images.githubusercontent.com/29310956/40826273-d076239a-6597-11e8-9554-28f52e7fe63d.png)

When I click on these buttons, technically they should redirect to the top of the page.

For example, if I click on how it works page.

it should redirect on the top of the how it works page.

instead, it opens up the bottom-most section of how it works page.

Please fix this.

Thanks!

**Comment by GAUTAMRAJU15** [comment]
componentDidMount(){
    window.scrollTo(0, 0);
  } 

this clears up the issue
